use crate::encoding::Encoding;
use crate::field::{FieldDesc, SubTab, Tier};
use crate::target::Target;

/// Sentinel stock value meaning "stock unknown / unverified"; the real-EXE
/// verification test skips fields carrying this value.
pub const STOCK_UNKNOWN: i64 = i64::MIN;

pub static PHYSICS_FIELDS: &[FieldDesc] = &[
    // ---- Engine ----
    FieldDesc {
        id: "rev_limiter",
        label: "Rev Limiter",
        help: "Engine rev limiter (legacy old-editor offset).",
        subtab: SubTab::Engine,
        tier: Tier::Basic,
        target: Target::Direct(1281904),
        width: 2,
        signed: false,
        encoding: Encoding::Raw,
        stock: STOCK_UNKNOWN, // legacy offset; verify
        range: None,
    },
    FieldDesc {
        id: "max_rpm",
        label: "Max RPM",
        help: "Maximum engine RPM (legacy old-editor offset).",
        subtab: SubTab::Engine,
        tier: Tier::Basic,
        target: Target::Direct(1281924),
        width: 2,
        signed: false,
        encoding: Encoding::Raw,
        stock: STOCK_UNKNOWN, // legacy offset; verify
        range: None,
    },
    FieldDesc {
        id: "rpm_light_1",
        label: "RPM Light 1",
        help: "Shift-light 1 RPM threshold (legacy old-editor offset).",
        subtab: SubTab::Engine,
        tier: Tier::Basic,
        target: Target::Direct(1284436),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: STOCK_UNKNOWN, // legacy; verify
        range: None,
    },
    FieldDesc {
        id: "rpm_light_2",
        label: "RPM Light 2",
        help: "Shift-light 2 RPM threshold (legacy old-editor offset).",
        subtab: SubTab::Engine,
        tier: Tier::Basic,
        target: Target::Direct(1284440),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: STOCK_UNKNOWN, // legacy; verify
        range: None,
    },
    FieldDesc {
        id: "rpm_light_3",
        label: "RPM Light 3",
        help: "Shift-light 3 RPM threshold (legacy old-editor offset).",
        subtab: SubTab::Engine,
        tier: Tier::Basic,
        target: Target::Direct(1284444),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: STOCK_UNKNOWN, // legacy; verify
        range: None,
    },
    FieldDesc {
        id: "rpm_light_4",
        label: "RPM Light 4",
        help: "Shift-light 4 RPM threshold (legacy old-editor offset).",
        subtab: SubTab::Engine,
        tier: Tier::Basic,
        target: Target::Direct(1284448),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: STOCK_UNKNOWN, // legacy; verify
        range: None,
    },
    FieldDesc {
        id: "soft_powercut_rpm",
        label: "Soft Power-cut RPM",
        help: "RPM at which engine power begins to be cut.",
        subtab: SubTab::Engine,
        tier: Tier::Advanced,
        target: Target::Data(0xD6010),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: 15200,
        range: None,
    },
    // ---- Aero ----
    FieldDesc {
        id: "df_scale",
        label: "Downforce Scale",
        help: "d_wingfactor (= old \"Downforce\").",
        subtab: SubTab::Aero,
        tier: Tier::Basic,
        target: Target::Data(0xD5EA8),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: 44369,
        range: None,
    },
    FieldDesc {
        id: "rear_df_slope",
        label: "Rear Downforce Slope",
        help: "Rear wing downforce slope.",
        subtab: SubTab::Aero,
        tier: Tier::Basic,
        target: Target::Code(0x1682D),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: 430,
        range: None,
    },
    FieldDesc {
        id: "rear_df_floor",
        label: "Rear Downforce Floor",
        help: "Rear wing downforce floor.",
        subtab: SubTab::Aero,
        tier: Tier::Basic,
        target: Target::Code(0x1683B),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: 2064,
        range: None,
    },
    FieldDesc {
        id: "rear_drag_slope",
        label: "Rear Drag Slope",
        help: "Rear wing drag slope.",
        subtab: SubTab::Aero,
        tier: Tier::Basic,
        target: Target::Code(0x168EC),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: 1259,
        range: None,
    },
    FieldDesc {
        id: "rear_drag_floor",
        label: "Rear Drag Floor",
        help: "Rear wing drag floor.",
        subtab: SubTab::Aero,
        tier: Tier::Basic,
        target: Target::Code(0x168FA),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: 1792,
        range: None,
    },
    FieldDesc {
        id: "front_wing_slope",
        label: "Front Wing Slope",
        help: "Front wing downforce slope.",
        subtab: SubTab::Aero,
        tier: Tier::Advanced,
        // Plan table listed IDA 0x1685F, but that address points directly at the
        // imm32 operand (opcode 0xBA `mov edx,imm32` sits at 0x1685E). Point Target
        // at the opcode so the +1 operand adjustment lands correctly. Verified
        // against real EXE: file off 0x8EAB3 reads 430 (= 0x1AE).
        target: Target::Code(0x1685E),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: 0x1AE,
        range: None,
    },
    FieldDesc {
        id: "front_wing_floor",
        label: "Front Wing Floor",
        help: "Front wing downforce floor.",
        subtab: SubTab::Aero,
        tier: Tier::Advanced,
        // Same correction as front_wing_slope: plan listed 0x1686D (the operand),
        // opcode 0x05 (`add eax,imm32`) is at 0x1686C. Verified against real EXE:
        // file off 0x8EAC1 reads 2064 (= 0x810).
        target: Target::Code(0x1686C),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: 0x810,
        range: None,
    },
    FieldDesc {
        id: "front_aero_scale",
        label: "Front Aero Scale",
        help: "Front aero scale factor.",
        subtab: SubTab::Aero,
        tier: Tier::Advanced,
        target: Target::Data(0xD5EA4),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: 0x18F5,
        range: None,
    },
    FieldDesc {
        id: "lateral_drag_x",
        label: "Lateral Drag X",
        help: "Lateral drag coefficient X.",
        subtab: SubTab::Aero,
        tier: Tier::Advanced,
        target: Target::Data(0xD5FD4),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: 0x1A00,
        range: None,
    },
    FieldDesc {
        id: "lateral_drag_y",
        label: "Lateral Drag Y",
        help: "Lateral drag coefficient Y.",
        subtab: SubTab::Aero,
        tier: Tier::Advanced,
        target: Target::Data(0xD5FD8),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: 0x5800,
        range: None,
    },
    FieldDesc {
        id: "rear_wing_drag_factor",
        label: "Rear Wing Drag Factor",
        help: "Rear wing drag factor.",
        subtab: SubTab::Aero,
        tier: Tier::Advanced,
        target: Target::Data(0xD53E0),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: 0x1000,
        range: None,
    },
    // ---- Brakes ----
    FieldDesc {
        id: "brake_force",
        label: "Brake Force",
        help: "Maximum braking force.",
        subtab: SubTab::Brakes,
        tier: Tier::Basic,
        target: Target::Data(0xD53FC),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: 0x160000,
        range: None,
    },
    FieldDesc {
        id: "brake_fail_mult",
        label: "Brake Fail Multiplier",
        help: "Brake failure multiplier.",
        subtab: SubTab::Brakes,
        tier: Tier::Advanced,
        target: Target::Data(0xD56A8),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: 0x1000,
        range: None,
    },
    FieldDesc {
        id: "abs_threshold",
        label: "ABS Threshold",
        help: "ABS activation threshold.",
        subtab: SubTab::Brakes,
        tier: Tier::Advanced,
        target: Target::Data(0xD5400),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: 0x3E800,
        range: None,
    },
    FieldDesc {
        id: "ai_brake_lookahead_1",
        label: "AI Brake Lookahead 1",
        help: "AI braking lookahead distance 1.",
        subtab: SubTab::Brakes,
        tier: Tier::Advanced,
        target: Target::Data(0xC9970),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: 0x3C00,
        range: None,
    },
    FieldDesc {
        id: "ai_brake_lookahead_2",
        label: "AI Brake Lookahead 2",
        help: "AI braking lookahead distance 2.",
        subtab: SubTab::Brakes,
        tier: Tier::Advanced,
        target: Target::Data(0xC9974),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: 0x3C00,
        range: None,
    },
    // ---- Mass / Grip ----
    FieldDesc {
        id: "std_weight",
        label: "Standard Weight",
        help: "Standard car weight.",
        subtab: SubTab::MassGrip,
        tier: Tier::Basic,
        target: Target::Data(0xD5E74),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: 1313,
        range: None,
    },
    FieldDesc {
        id: "norm_weight",
        label: "Normal Weight",
        help: "Normal car weight.",
        subtab: SubTab::MassGrip,
        tier: Tier::Basic,
        target: Target::Data(0xD5E78),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: 1313,
        range: None,
    },
    FieldDesc {
        id: "gravity",
        label: "Gravity",
        help: "Gravity constant (signed).",
        subtab: SubTab::MassGrip,
        tier: Tier::Advanced,
        target: Target::Data(0xD5EA0),
        width: 4,
        signed: true,
        encoding: Encoding::Raw,
        stock: -0x80000,
        range: None,
    },
    FieldDesc {
        id: "fuel_factor",
        label: "Fuel Factor",
        help: "Fuel mass factor.",
        subtab: SubTab::MassGrip,
        tier: Tier::Advanced,
        target: Target::Data(0xD57D8),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: 1627167,
        range: None,
    },
    FieldDesc {
        id: "packer_factor",
        label: "Packer Factor",
        help: "Suspension packer factor.",
        subtab: SubTab::MassGrip,
        tier: Tier::Advanced,
        target: Target::Data(0xD54B4),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: 0xD70340,
        range: None,
    },
    FieldDesc {
        id: "rebound_factor",
        label: "Rebound Factor",
        help: "Suspension rebound factor.",
        subtab: SubTab::MassGrip,
        tier: Tier::Advanced,
        target: Target::Data(0xD54C8),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: 0x546000,
        range: None,
    },
    FieldDesc {
        id: "min_grip_clamp",
        label: "Min Grip Clamp",
        help: "Minimum grip clamp.",
        subtab: SubTab::MassGrip,
        tier: Tier::Advanced,
        target: Target::Data(0xD5E3E),
        width: 2,
        signed: false,
        encoding: Encoding::Hex,
        stock: 0x2C00,
        range: None,
    },
    FieldDesc {
        id: "cc_grip_qual",
        label: "CC Grip (Qualifying)",
        help: "Overall computer-controlled grip in qualifying.",
        subtab: SubTab::MassGrip,
        tier: Tier::Basic,
        target: Target::Data(0xD5974),
        width: 2,
        signed: false,
        encoding: Encoding::Raw,
        stock: 0x40CC,
        range: None,
    },
    FieldDesc {
        id: "cc_grip_race",
        label: "CC Grip (Race)",
        help: "Overall computer-controlled grip in race.",
        subtab: SubTab::MassGrip,
        tier: Tier::Basic,
        target: Target::Data(0xD5978),
        width: 2,
        signed: false,
        encoding: Encoding::Raw,
        stock: 0x40CC,
        range: None,
    },
    // ---- Slipstream / Tow ----
    FieldDesc {
        id: "tow_strength",
        label: "Tow Strength",
        help: "Slipstream tow strength (0 = off).",
        subtab: SubTab::Slipstream,
        tier: Tier::Basic,
        target: Target::Data(0xD53DC),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: 0x40000,
        range: None,
    },
    FieldDesc {
        id: "tow_reach",
        label: "Tow Reach",
        help: "Slipstream reach.",
        subtab: SubTab::Slipstream,
        tier: Tier::Basic,
        target: Target::Data(0xC9750),
        width: 2,
        signed: false,
        encoding: Encoding::Raw,
        stock: 0x180,
        range: None,
    },
    FieldDesc {
        id: "tow_align_width",
        label: "Tow Align Width",
        help: "Slipstream alignment width.",
        subtab: SubTab::Slipstream,
        tier: Tier::Basic,
        target: Target::Data(0xC9748),
        width: 2,
        signed: false,
        encoding: Encoding::Raw,
        stock: 0x200,
        range: None,
    },
    FieldDesc {
        id: "ai_tow_strength",
        label: "AI Tow Strength",
        help: "AI slipstream tow strength (dormant; set >0).",
        subtab: SubTab::Slipstream,
        tier: Tier::Basic,
        target: Target::Data(0xD5FF4),
        width: 4,
        signed: false,
        encoding: Encoding::Raw,
        stock: 0,
        range: None,
    },
    FieldDesc {
        id: "tow_max_wake",
        label: "Tow Max Wake",
        help: "Maximum slipstream wake.",
        subtab: SubTab::Slipstream,
        tier: Tier::Advanced,
        target: Target::Data(0xC9752),
        width: 2,
        signed: false,
        encoding: Encoding::Raw,
        stock: 0x100,
        range: None,
    },
    FieldDesc {
        id: "tow_max_range",
        label: "Tow Max Range",
        help: "Maximum slipstream range.",
        subtab: SubTab::Slipstream,
        tier: Tier::Advanced,
        target: Target::Data(0xC9766),
        width: 2,
        signed: false,
        encoding: Encoding::Raw,
        stock: 7,
        range: None,
    },
    FieldDesc {
        id: "tow_min_speed",
        label: "Tow Min Speed",
        help: "Minimum speed for slipstream.",
        subtab: SubTab::Slipstream,
        tier: Tier::Advanced,
        target: Target::Data(0xD5D96),
        width: 2,
        signed: false,
        encoding: Encoding::Raw,
        stock: 0xB00,
        range: None,
    },
    // ai_follow_base_1..7 (7 signed thresholds, Hex)
    FieldDesc {
        id: "ai_follow_base_1",
        label: "AI Follow Base 1",
        help: "AI following threshold 1 (signed).",
        subtab: SubTab::Slipstream,
        tier: Tier::Advanced,
        target: Target::Data(0xC96CA),
        width: 2,
        signed: true,
        encoding: Encoding::Hex,
        stock: -4096, // 0xF000 as signed i16
        range: None,
    },
    FieldDesc {
        id: "ai_follow_base_2",
        label: "AI Follow Base 2",
        help: "AI following threshold 2 (signed).",
        subtab: SubTab::Slipstream,
        tier: Tier::Advanced,
        target: Target::Data(0xC96CC),
        width: 2,
        signed: true,
        encoding: Encoding::Hex,
        stock: -3072, // 0xF400 as signed i16
        range: None,
    },
    FieldDesc {
        id: "ai_follow_base_3",
        label: "AI Follow Base 3",
        help: "AI following threshold 3 (signed).",
        subtab: SubTab::Slipstream,
        tier: Tier::Advanced,
        target: Target::Data(0xC96D2),
        width: 2,
        signed: true,
        encoding: Encoding::Hex,
        stock: -24576, // 0xA000 as signed i16
        range: None,
    },
    FieldDesc {
        id: "ai_follow_base_4",
        label: "AI Follow Base 4",
        help: "AI following threshold 4 (signed).",
        subtab: SubTab::Slipstream,
        tier: Tier::Advanced,
        target: Target::Data(0xC96D4),
        width: 2,
        signed: true,
        encoding: Encoding::Hex,
        stock: -1024, // 0xFC00 as signed i16
        range: None,
    },
    FieldDesc {
        id: "ai_follow_base_5",
        label: "AI Follow Base 5",
        help: "AI following threshold 5 (signed).",
        subtab: SubTab::Slipstream,
        tier: Tier::Advanced,
        target: Target::Data(0xC96D8),
        width: 2,
        signed: true,
        encoding: Encoding::Hex,
        stock: -2048, // 0xF800 as signed i16
        range: None,
    },
    FieldDesc {
        id: "ai_follow_base_6",
        label: "AI Follow Base 6",
        help: "AI following threshold 6 (signed).",
        subtab: SubTab::Slipstream,
        tier: Tier::Advanced,
        target: Target::Data(0xC96DA),
        width: 2,
        signed: true,
        encoding: Encoding::Hex,
        stock: -4096, // 0xF000 as signed i16
        range: None,
    },
    FieldDesc {
        id: "ai_follow_base_7",
        label: "AI Follow Base 7",
        help: "AI following threshold 7 (signed).",
        subtab: SubTab::Slipstream,
        tier: Tier::Advanced,
        target: Target::Data(0xC96DC),
        width: 2,
        signed: true,
        encoding: Encoding::Hex,
        stock: -512, // 0xFE00 as signed i16
        range: None,
    },
    // ai_follow_floor_1..3 (Hex, u32)
    FieldDesc {
        id: "ai_follow_floor_1",
        label: "AI Follow Floor 1",
        help: "AI following floor 1.",
        subtab: SubTab::Slipstream,
        tier: Tier::Advanced,
        target: Target::Data(0xD5FE8),
        width: 4,
        signed: false,
        encoding: Encoding::Hex,
        stock: 0xFC00,
        range: None,
    },
    FieldDesc {
        id: "ai_follow_floor_2",
        label: "AI Follow Floor 2",
        help: "AI following floor 2.",
        subtab: SubTab::Slipstream,
        tier: Tier::Advanced,
        target: Target::Data(0xD5FEC),
        width: 4,
        signed: false,
        encoding: Encoding::Hex,
        stock: 0xD000,
        range: None,
    },
    FieldDesc {
        id: "ai_follow_floor_3",
        label: "AI Follow Floor 3",
        help: "AI following floor 3.",
        subtab: SubTab::Slipstream,
        tier: Tier::Advanced,
        target: Target::Data(0xD5FF0),
        width: 4,
        signed: false,
        encoding: Encoding::Hex,
        stock: 0x5000,
        range: None,
    },
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unique_ids() {
        let mut ids: Vec<&str> = PHYSICS_FIELDS.iter().map(|f| f.id).collect();
        ids.sort();
        let len = ids.len();
        ids.dedup();
        assert_eq!(ids.len(), len, "duplicate field id found");
    }

    #[test]
    fn stock_values_match_real_exe() {
        let Ok(p) = std::env::var("GP2WS_TEST_EXE") else {
            return;
        }; // skip if unset
        let img = crate::exe::ExeImage::load(std::path::Path::new(&p)).unwrap();
        let crate::calibration::Calibration::Calibrated { delta } =
            crate::calibration::calibrate(&img)
        else {
            panic!("not calibrated")
        };
        for f in PHYSICS_FIELDS {
            if f.stock == i64::MIN {
                continue; // sentinel for "unknown stock"
            }
            assert_eq!(
                f.read(&img, delta),
                crate::encoding::decode(f.stock, f.encoding),
                "field {} mismatch",
                f.id
            );
        }
    }
}
